mysql:
 - 
   host: 10.142.116.177
   port: 3306
   dbname: test
   user: root
   password: setest520123
   charset: utf8
 - 
   host: 10.142.116.187
   port: 3306
   dbname: test
   user: root
   password: setest520123
   charset: utf8
redis:
 - 
   host: 10.142.116.177
   port: 6379
   password: 
   dbindex: 0
 - 
   host: 10.142.116.197
   port: 6377
   password: 
   dbindex: 0